name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build do projeto
        run: dotnet publish -c Release -o release

      - name: Copiar arquivos para publicação
        run: |
          mkdir gh-pages
          cp -r release/wwwroot/* gh-pages/
          touch gh-pages/.nojekyll

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
